services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - /var/www/node_modules
        networks:
            - app-network
        ports:
            - "8000:8000"
            - "5173:5173"
        depends_on:
            - db

    reverb:
        build:
            context: .
            dockerfile: reverb/Dockerfile
        container_name: laravel_reverb
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        ports:
            - "8081:8081"
            - "8082:8082"
        environment:
            - REVERB_SERVER_PORT=8082

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        restart: unless-stopped
        ports:
            - "8083:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-network
        depends_on:
            - db
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
